version: 2
jobs:
  build:
    working_directory: /go/src/github.com/SignifAi/snap-plugin-publisher-pubsub
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - run:
          command: |
            echo "---"
            curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-155.0.0-linux-x86_64.tar.gz
            tar xzf google-cloud-sdk-155.0.0-linux-x86_64.tar.gz
            cd google-cloud-sdk
            sh ./install.sh -q --additional-components pubsub-emulator --usage-reporting false
            cd ..
            sh -c 'echo "gcloud? $(which gcloud) PATH $PATH"'
            echo "Fetching glide; note GOPATH is $GOPATH"
            curl http://glide.sh/get | /bin/bash
            echo "Building"
            git config --global url.git@github.com:.insteadOf https://github.com/
            make
            echo "Testing"
            sh -c 'make test'
